### ISSUE TITLE
ParMETIS should not be a mandatory dependency

### ISSUE THREAD

**Issue by jeffhammond** [lanl/branson#12]
The ParMETIS [license](http://glaros.dtc.umn.edu/gkhome/metis/parmetis/download) does not appear to permit use by for-profit institutions regardless of their purpose.  This would seem to preclude use by HPC vendors for co-design or benchmarking purposes.

> ParMETIS is copyrighted by the Regents of the University of Minnesota. It can be freely used for educational and research purposes by non-profit institutions and US government agencies only. Other organizations are allowed to use ParMETIS only for evaluation purposes, and any further uses will require prior approval. The software may not be sold or redistributed without prior approval. One may make copies of the software for their use provided that the copies, are not sold or distributed, are used under the same terms and conditions.

**Comment by alexrlongne** [comment]
Thanks for pointing this out. I hadn't considered this. I'll talk to some people here and also see if I can make a very simple partitioner for a truly open version of Branson.

**Comment by jeffhammond** [comment]
I don't know about METIS vs ParMETIS but for my purposes, it's fine to map whatever ParMETIS is doing to METIS on rank 0 and broadcast the results.

**Comment by alexrlongne** [comment]
Metis is under Apache 2.0, which looks like it allows commercial use. I can definitely do a Metis plus a broadcast. Thanks!

**Comment by alexrlongne** [comment]
@jeffhammond I've removed the Parmetis dependency from the code base. I use now use Metis and broadcast, thanks for the suggestion!
